/// BQ Job Details Fact Table
table Fact
	lineageTag: f68bc297-43df-4f43-99b6-c80a83cb3dcb

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: month
		rollingWindowPeriods: 5
		incrementalGranularity: day
		incrementalPeriods: 2
		sourceExpression =
			let
			    SqlTemplate =
			"
			WITH src AS (
			  -- Filter BEFORE resolving labels so the label pass only runs on kept rows.
			  SELECT *,
			    (SELECT AS STRUCT
			       MAX(IF(key = 'app',           value, NULL)) AS app,
			       MAX(IF(key = 'project',       value, NULL)) AS project,
			       MAX(IF(key = 'env',           value, NULL)) AS env,
			       MAX(IF(key = 'model_name',    value, NULL)) AS model_name,
			       MAX(IF(key = 'resource_type', value, NULL)) AS resource_type,
			       -- dbt-bigquery's OWN label, not one added by this project's query_comment. Present on
			       -- every job dbt submits, including post-hook and run-operation jobs that dbt_artifacts
			       -- never records, and history predating any query_comment change. Equals
			       -- dbt_invocations[command_invocation_id]. Do not swap this for a hand-added run id: a
			       -- per-run value in the query comment also defeats BigQuery's result cache.
			       MAX(IF(key = 'dbt_invocation_id', value, NULL)) AS invocation_id
			     FROM UNNEST(labels)) AS lbl
			  FROM __TABLE__
			  WHERE
			    NOT query like '%INFORMATION_SCHEMA.%'
			    AND state = 'DONE'
			    -- On-demand jobs only. Under a reservation you pay for slot capacity, not bytes, and
			    -- total_bytes_billed keeps being reported without being charged - so reserved jobs would
			    -- add cost to every dollar measure here that nobody was ever billed for. Cost measures
			    -- price bytes, so the fact is scoped to the jobs that pricing model actually applies to.
			    AND reservation_id IS NULL
			    AND creation_time >= TIMESTAMP('" & DateTime.ToText(RangeStart, "yyyy-MM-dd HH:mm:ss") & "')
			    AND creation_time < TIMESTAMP('" & DateTime.ToText(RangeEnd, "yyyy-MM-dd HH:mm:ss") & "')
			),
			
			-- A multi-statement SCRIPT's parent job has no destination_table of its own: the write targets sit
			-- on its child statements. Without this, every script-based model (incrementals, MERGE) collapses
			-- into a single blank bucket -- measured at ~22% of dbt spend. Adopt the destination of the child
			-- that billed the most. Label-independent, so it also repairs history written by a dbt deployment
			-- whose query_comment carried no node name.
			child_dest AS (
			  SELECT
			    parent_job_id,
			    ARRAY_AGG(destination_table.table_id IGNORE NULLS ORDER BY total_bytes_billed DESC LIMIT 1)[SAFE_OFFSET(0)] AS child_table_id
			  FROM src
			  WHERE parent_job_id IS NOT NULL
			  GROUP BY parent_job_id
			),
			
			joined AS (
			  SELECT a.*, COALESCE(a.destination_table.table_id, c.child_table_id) AS raw_dest_table_id
			  FROM src a
			  LEFT JOIN child_dest c ON a.job_id = c.parent_job_id
			)
			
			SELECT
			  '__REGION__' as region,
			  job_id,
			  parent_job_id,
			  user_email,
			  -- Labels: ONE pass over the labels array (was six correlated subqueries).
			  lbl.app AS label_app,
			  lbl.project AS label_project,
			  lbl.env AS label_env,
			  lbl.model_name AS label_model_name,
			  lbl.resource_type AS label_resource_type,
			  lbl.invocation_id AS label_invocation_id,
			  -- Single source of truth for dbt scope. The BigQuery adapter stamps an invocation id on every
			  -- job dbt submits, so this also catches post-hook and run-operation jobs that the run metadata
			  -- never records. Scoping on the app label instead would omit every job submitted without it.
			  -- Every dbt measure and the dbt_attribution column key off this column, so the definition
			  -- changes in one place.
			  lbl.invocation_id IS NOT NULL AS is_dbt_job,
			
			  CASE
			    WHEN statement_type is null THEN 'FAILED'
			    ELSE statement_type
			  END as statement_type,
			  -- The leading /* ... */ query comment is stripped from BOTH the hash and the stored SQL: dbt's
			  -- query_comment carries a per-run invocation_id, which would otherwise make every dbt query
			  -- text unique per run and defeat queryhash dedup. The labels are already columns above.
			  CAST(FARM_FINGERPRINT(REGEXP_REPLACE(query, r'(?s)^\s*/\*.*?\*/\s*', '')) as STRING) as queryhash,
			  REGEXP_REPLACE(query, r'(?s)^\s*/\*.*?\*/\s*', '') as query,
			  cast(creation_time as date) as creation_date,
			  cast(creation_time as time) as creation_time,
			  EXTRACT(HOUR FROM creation_time) AS creation_hour_24,
			  start_time,
			  end_time,
			  TIMESTAMP_DIFF(end_time, start_time, SECOND) AS duration_sec,
			  cache_hit,
			  error_result.reason as error_reason,
			  error_result.location as error_location,
			  error_result.message as error_message,
			  total_bytes_processed,
			  total_bytes_billed,
			  total_slot_ms,
			  TIME(TIMESTAMP_MICROS(total_slot_ms * 1000)) AS total_slot_hr,
			  -- Destination table, normalised:
			  --   SCRIPT parent   -> inherited from its largest child (see child_dest above)
			  --   *__dbt_tmp      -> folded into the parent model, so one model is one bar
			  --   anon*           -> collapsed into a single bucket. These are SELECT results. Kept VISIBLE,
			  --                      not nulled, since they can be a real and surprising share of spend.
			  CASE
			    WHEN a.raw_dest_table_id IS NULL THEN NULL
			    WHEN STARTS_WITH(a.raw_dest_table_id, 'anon') THEN '(anonymous SELECT result)'
			    ELSE REGEXP_REPLACE(a.raw_dest_table_id, r'__dbt_tmp$', '')
			  END AS destination_table_id,
			
			  CASE
			    WHEN total_bytes_processed < 1048576 THEN 1
			    WHEN total_bytes_processed < 104857600 THEN 2
			    WHEN total_bytes_processed < 1073741824 THEN 3
			    ELSE 4
			  END AS DataSizeCategoryID,
			  ---bie---
			  COALESCE(bi_engine_statistics.bi_engine_mode, 'NOT APPLICABLE') AS bie_mode,
			  (
			    SELECT STRING_AGG(r.code, ', ')
			    FROM UNNEST(bi_engine_statistics.bi_engine_reasons) r
			  ) AS bie_error_code,
			
			  (
			    SELECT STRING_AGG(r.message, ' | ')
			    FROM UNNEST(bi_engine_statistics.bi_engine_reasons) r
			  ) AS bie_error_reason
			
			FROM joined a
			",
			
			    // Regions come from the p_Regions parameter.
			    Regions = List.Transform(Text.Split(p_Regions, ","), Text.Trim),
			
			    Tables = List.Transform(
			        Regions,
			        (r) =>
			            try fx_GetJobdetails(r, SqlTemplate)
			            otherwise null
			    ),
			
			    // Remove failed/null queries
			    CleanTables = List.RemoveNulls(Tables),
			
			    Combined = Table.Combine(CleanTables),
			
			    // Sample-data branch. The date filter is not optional: the refresh
			    // policy above binds RangeStart/RangeEnd per partition, and a CSV read
			    // that ignored them would return every row for every partition.
			    _csv = () =>
			        let
			            _all = fn_ReadSampleCsv("jobs.csv", {
			            {"job_id", type text}, {"creation_date", type date}, {"creation_time", type time}, {"start_time", type datetime},
			            {"end_time", type datetime}, {"duration_sec", Int64.Type}, {"cache_hit", type logical}, {"creation_hour_24", Int64.Type},
			            {"total_slot_hr", type time}, {"DataSizeCategoryID", Int64.Type}, {"total_bytes_processed", Int64.Type}, {"total_bytes_billed", Int64.Type},
			            {"error_reason", type text}, {"error_location", type text}, {"error_message", type text}, {"user_email", type text},
			            {"statement_type", type text}, {"queryhash", type text}, {"region", type text}, {"bie_mode", type text},
			            {"label_app", type text}, {"label_project", type text}, {"bie_error_code", type text}, {"bie_error_reason", type text},
			            {"label_env", type text}, {"parent_job_id", type text}, {"label_model_name", type text}, {"label_resource_type", type text},
			            {"label_invocation_id", type text}, {"total_slot_ms", Int64.Type}, {"destination_table_id", type text}, {"query", type text},
			            {"is_dbt_job", type logical}
			            }),
			            _window = Table.SelectRows(
			                _all,
			                each [creation_date] >= DateTime.Date(RangeStart)
			                    and [creation_date] < DateTime.Date(RangeEnd)
			            )
			        in
			            _window,
			
			    Source = if p_DataSource = "SampleCSV" then _csv() else Combined
			in
			    Source

	/// BigQuery's unique identifier for the job. The grain of this table - one row per job - and the key that ties a job to its dbt node metadata.
	column job_id
		dataType: string
		lineageTag: 1ab37b5f-d855-4d3a-9ba4-71c13c9daa53
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	/// Date the job was submitted. The field the date slicer drives, and the basis of the rolling incremental-refresh window.
	column creation_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: d3f70874-8d10-484b-b9b0-5e562a961555
		summarizeBy: none
		sourceColumn: creation_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Time of day the job was submitted, for reading load concentration within a day.
	column creation_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5ed72d34-7004-4e64-b279-eb3099a0678b
		summarizeBy: none
		sourceColumn: creation_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// When the job began executing. The gap from submission to start is queue wait.
	column start_time
		dataType: dateTime
		formatString: General Date
		lineageTag: f97dd3a5-a7aa-490e-a38f-06e0605c58c5
		summarizeBy: none
		sourceColumn: start_time

		annotation SummarizationSetBy = Automatic

	/// When the job finished, successfully or not.
	column end_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c5268da-7064-4ba1-87c1-fce33d1ae58f
		summarizeBy: none
		sourceColumn: end_time

		annotation SummarizationSetBy = Automatic

	/// Wall-clock seconds from start to finish. What a user experiences as slowness - note it does not track cost, since a long job can scan very little and a fast one can scan a great deal.
	column duration_sec
		dataType: int64
		formatString: 0
		lineageTag: 08284f23-5c2f-4fdd-aaab-a7e2d2c5ece0
		summarizeBy: sum
		sourceColumn: duration_sec

		annotation SummarizationSetBy = Automatic

	/// TRUE when BigQuery served the result from cache. Cached results are not billed, so a healthy cache-hit rate on repeated queries is a direct saving.
	column cache_hit
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dab6569d-1e86-48c9-ad9d-e10febd1b4b3
		summarizeBy: none
		sourceColumn: cache_hit

		annotation SummarizationSetBy = Automatic

	/// Hour of submission on a 24-hour clock. Join key to the time-of-day dimension.
	column creation_hour_24
		dataType: int64
		formatString: 0
		lineageTag: 37cab1b6-1b37-4985-a7de-6bea5ec8b449
		summarizeBy: none
		sourceColumn: creation_hour_24

		annotation SummarizationSetBy = Automatic

	/// Slot hours consumed, as BigQuery accounts them - the compute the job actually used. This is the figure that matters under slot or reservation pricing, where cost tracks compute time rather than bytes scanned.
	column total_slot_hr
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5227f1a5-89b3-4697-92ef-ebd710d5dd4f
		summarizeBy: none
		sourceColumn: total_slot_hr

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	/// Join key to the size-band dimension, assigned from bytes processed. Lets query volume be profiled by scan size without banding in DAX.
	column DataSizeCategoryID
		dataType: int64
		formatString: 0
		lineageTag: e7d009d6-1e23-4c17-bc85-e1da51204f2d
		summarizeBy: none
		sourceColumn: DataSizeCategoryID

		annotation SummarizationSetBy = Automatic

	/// Bytes the job actually scanned. Not what Google charges for - see total_bytes_billed.
	column total_bytes_processed
		dataType: int64
		formatString: 0
		lineageTag: 41b3612c-da7e-4647-9d13-4ce78057d084
		summarizeBy: sum
		sourceColumn: total_bytes_processed

		annotation SummarizationSetBy = Automatic

	/// Bytes charged for, which is what every cost figure derives from. It already includes BigQuery's per-query minimum and its rounding increment, so on small queries it can exceed bytes scanned. Aggregate it only over top-level jobs, or a multi-statement script is counted twice.
	column total_bytes_billed
		dataType: int64
		formatString: 0
		lineageTag: 4a6415e0-4858-46e8-9c8c-102e83474fe6
		summarizeBy: sum
		sourceColumn: total_bytes_billed

		annotation SummarizationSetBy = Automatic

	/// Short error code when the job failed - the field to group by when profiling failure modes.
	column error_reason
		dataType: string
		lineageTag: e9a618b3-76f6-417f-a291-73ec54a70f92
		summarizeBy: none
		sourceColumn: error_reason

		annotation SummarizationSetBy = Automatic

	/// Where in the query or resource the error was raised, when BigQuery reports it.
	column error_location
		dataType: string
		lineageTag: 60c1f784-edd6-4f88-bd3a-fddcacf41443
		summarizeBy: none
		sourceColumn: error_location

		annotation SummarizationSetBy = Automatic

	/// Full error text, for diagnosis on drillthrough rather than aggregation.
	column error_message
		dataType: string
		lineageTag: 3b1a862f-c979-4248-bede-04215a80950a
		summarizeBy: none
		sourceColumn: error_message

		annotation SummarizationSetBy = Automatic

	/// The account that submitted the job - a service account for scheduled pipelines, a person for ad-hoc work. The main lens for attributing spend to a team or a tool.
	column user_email
		dataType: string
		lineageTag: 6ea4fa52-1db2-4e57-8825-493bf57469b6
		summarizeBy: none
		sourceColumn: user_email

		annotation SummarizationSetBy = Automatic

	/// The kind of statement submitted: a SELECT, an INSERT or MERGE, a SCRIPT wrapping several statements, and so on. Failed jobs are marked FAILED here.
	column statement_type
		dataType: string
		lineageTag: 3209400c-cea0-4cee-885e-eb5013e48cf0
		summarizeBy: none
		sourceColumn: statement_type

		annotation SummarizationSetBy = Automatic

	/// Fingerprint of the normalised query text. Groups repeated executions of the same query, which is how repeat cost and cache effectiveness are measured.
	column queryhash
		dataType: string
		lineageTag: f3c780ed-1d77-4ef7-8d17-894ea947f36f
		summarizeBy: none
		sourceColumn: queryhash

		annotation SummarizationSetBy = Automatic

	/// BigQuery region the job ran in. Drives the per-region rate lookup behind the cost measures, since on-demand pricing differs by region.
	column region
		dataType: string
		lineageTag: af6b1c74-d203-4e0a-8abf-0d9cbd9d8f22
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	/// How far BI Engine accelerated the job - fully, partially, or not at all. Acceleration cuts both latency and billed bytes, so this is a tuning lever for interactive workloads.
	column bie_mode
		dataType: string
		lineageTag: 171c1278-fb49-428c-93c6-0fc7afc5d519
		summarizeBy: none
		sourceColumn: bie_mode

		annotation SummarizationSetBy = Automatic

	/// Job label naming the tool that submitted the job. Useful for splitting spend by tool, but do not use it to define dbt scope - it is only present when a project is configured to emit it. Scope dbt work on is_dbt_job instead.
	column label_app
		dataType: string
		lineageTag: 128bd639-9557-4073-bb3f-3b57e364d559
		summarizeBy: none
		sourceColumn: label_app

		annotation SummarizationSetBy = Automatic

	/// Job label naming the project or codebase the job came from.
	column label_project
		dataType: string
		lineageTag: 6e1ae73e-7eab-4229-94f0-8c2ac8762a4b
		summarizeBy: none
		sourceColumn: label_project

		annotation SummarizationSetBy = Automatic

	/// Code explaining why BI Engine could not accelerate the job.
	column bie_error_code
		dataType: string
		lineageTag: b7033387-6f43-487b-8b8b-7480e14ac27f
		summarizeBy: none
		sourceColumn: bie_error_code

		annotation SummarizationSetBy = Automatic

	/// Readable reason BI Engine declined the job - typically an unsupported construct or insufficient capacity. Read it to judge whether a query can be reshaped to qualify.
	column bie_error_reason
		dataType: string
		lineageTag: 01c08d25-5ef6-48b6-b089-0b7ddb0b9051
		summarizeBy: none
		sourceColumn: bie_error_reason

		annotation SummarizationSetBy = Automatic

	/// Job label naming the environment - production, staging, development. The quickest way to see how much non-production work is being paid for.
	column label_env
		dataType: string
		lineageTag: ac8aa055-b975-46ff-8c9f-63fbd148a2f6
		summarizeBy: none
		sourceColumn: label_env

		annotation SummarizationSetBy = Automatic

	/// Job ID of the parent SCRIPT job when this job is one statement of a multi-statement script. BLANK for top-level jobs. Child statements DO bill, and the parent SCRIPT job reports the exact sum of its children's billed bytes - both rows are present here, so any cost measure must restrict to top-level jobs (parent_job_id is BLANK) or it double counts the whole script.
	column parent_job_id
		dataType: string
		lineageTag: 358a6eb9-cb52-4ed8-88bf-03adfac9d872
		summarizeBy: none
		sourceColumn: parent_job_id

	/// dbt job label naming the node that caused this job. Also present on jobs fired from inside a model's post-hooks, which is the only route to attributing post-hook spend to a model - those are separate job submissions and never appear in dbt's own run metadata. Only populated where the dbt project emits job labels through its query comment; where it does not, such jobs fall to the run-level attribution bucket.
	column label_model_name
		dataType: string
		lineageTag: d93f4feb-9a33-4f7f-92ae-4bfc2712c56f
		summarizeBy: none
		sourceColumn: label_model_name

	/// dbt job label: model, test, snapshot or operation. Blank when dbt had no node context (metadata queries, run-operation, on-run-end hooks).
	column label_resource_type
		dataType: string
		lineageTag: 131343bf-f10f-4111-ad60-03b5614b8c34
		summarizeBy: none
		sourceColumn: label_resource_type

	/// The dbt run that fired this job, from the invocation-id label the BigQuery adapter stamps on every job it submits. Joins to the run metadata. Because the adapter sets it natively rather than the project's query comment, it also covers post-hook and run-operation jobs that the metadata package never records. Do NOT add a run-id of your own to the query comment - it would duplicate this label and would defeat BigQuery's result cache, which keys on exact query text including comments, turning every repeated query into a cache miss.
	column label_invocation_id
		dataType: string
		lineageTag: 9d46d795-5317-4df7-a86b-50b790877ae4
		summarizeBy: none
		sourceColumn: label_invocation_id

	/// Raw slot milliseconds consumed. Aggregable, unlike total_slot_hr which is cast to TIME.
	column total_slot_ms
		dataType: int64
		formatString: #,0
		lineageTag: 7de912c2-d637-46a7-923f-2c6bcf7b3834
		summarizeBy: sum
		sourceColumn: total_slot_ms

	/// Table this job wrote to, normalised two ways: dbt's incremental temp-table suffix is stripped so a model appears as a single value rather than split between itself and its temp table, and BigQuery's anonymous result tables collapse into one '(anonymous SELECT result)' bucket. Independent of both labels and dbt metadata and it works retroactively, since a job writing to a model's relation is that model. BLANK for jobs with no target table, such as plain SELECTs and multi-statement script parents.
	column destination_table_id
		dataType: string
		lineageTag: f626938c-52b1-4042-abf4-6368c441c7c2
		summarizeBy: none
		sourceColumn: destination_table_id

	/// How confidently this BigQuery job can be tied to a dbt node. 'Node (dbt metadata)' = matched to a recorded node execution by job id, the most precise. 'Node (label)' = identified by the model-name and resource-type job labels, which is the only route for post-hook jobs. 'Run-level' = a dbt job with a run id but no identifiable node, such as a run-operation, an on-run-end hook, or a job submitted without node labels. 'Non-dbt' = everything else, for example reporting and ad-hoc queries. Keyed off is_dbt_job rather than the app label, so no dbt job is misfiled as non-dbt.
	column dbt_attribution =
			SWITCH (
			    TRUE (),
			    NOT 'Fact'[is_dbt_job], "Non-dbt",
			    NOT ISBLANK ( RELATED ( 'dbt_node_executions'[node_execution_id] ) ), "Node (dbt metadata)",
			    NOT ISBLANK ( 'Fact'[label_resource_type] ), "Node (label)",
			    "Run-level"
			)
		dataType: string
		lineageTag: 4d03f37d-ac7f-4a60-a0d5-c69525334908
		summarizeBy: none

	/// The SQL text BigQuery executed, with dbt's leading /* ... */ query comment stripped - its contents are already broken out into the label_* columns. Held on the job row itself rather than in a separate detail table, so drillthrough reaches it without a many-to-many hop.
	column query
		dataType: string
		lineageTag: fbeebf00-7ed2-4e27-a660-776cbba23724
		summarizeBy: none
		sourceColumn: query

	/// Whether this BigQuery job was submitted by dbt. TRUE when the adapter-native invocation-id label is present, which it is on every job dbt submits - post-hook and run-operation jobs included. This is the single source of truth for dbt scope: every dbt measure and the dbt_attribution column key off it, so the definition changes in one place. Do NOT scope dbt measures on the app label instead - that label is only emitted where a project explicitly configures it, so it silently omits any job submitted without it.
	column is_dbt_job
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4f1c8a52-3d77-4b6e-9c21-7ae03d9b58c4
		summarizeBy: none
		sourceColumn: is_dbt_job

	/// One label per dbt run, built from the invocation id stamped on the BigQuery job. Reads as the run's submission timestamp plus the first 8 characters of the invocation id - the timestamp so runs sort and read chronologically, the id fragment so two runs starting in the same minute stay separate rows and so a run can be traced back to the dbt logs. Derived from Fact, not from dbt_invocations, so it covers every dbt run present in the billing data rather than only the runs the dbt_artifacts dataset still retains. Covers tests and hooks as well as model builds, so the label deliberately says nothing about which dbt command was used.
	column 'dbt Run' =
			VAR _Inv = 'Fact'[label_invocation_id]
			VAR _Start =
			    CALCULATE (
			        MINX ( 'Fact', 'Fact'[creation_date] + 'Fact'[creation_time] ),
			        ALLEXCEPT ( 'Fact', 'Fact'[label_invocation_id] )
			    )
			RETURN
			    IF (
			        ISBLANK ( _Inv ),
			        BLANK (),
			        "Run " & FORMAT ( _Start, "yyyy-mm-dd hh:nn" ) & " [" & LEFT ( _Inv, 8 ) & "]"
			    )
		dataType: string
		lineageTag: 7cf74ca1-6218-4503-abb6-da1719f603a8
		summarizeBy: none

	/// Wall-clock runtime band for a job, for reading the shape of the duration distribution rather than a single average. Bands are sub-second, 1-5s, 5-15s, 15-60s and over a minute. The 15s boundary is deliberate: it is the same threshold Slow Queries (>15s) and Slow Query Rate % use, so the band chart and the KPI card cannot disagree.
	column 'Runtime Band' =
			SWITCH (
			    TRUE (),
			    'Fact'[duration_sec] < 1, "0-1s",
			    'Fact'[duration_sec] < 5, "1-5s",
			    'Fact'[duration_sec] < 15, "5-15s",
			    'Fact'[duration_sec] < 60, "15-60s",
			    "60s+"
			)
		dataType: string
		lineageTag: 9f3c1a54-6ad2-4c8b-9f21-3e7b04d5c111
		summarizeBy: none
		sortByColumn: 'Runtime Band Order'

	/// Display order for Runtime Band. Hidden - sort key only.
	column 'Runtime Band Order' =
			SWITCH (
			    TRUE (),
			    'Fact'[duration_sec] < 1, 0,
			    'Fact'[duration_sec] < 5, 1,
			    'Fact'[duration_sec] < 15, 2,
			    'Fact'[duration_sec] < 60, 3,
			    4
			)
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2c8e77b1-5f40-4de6-8a19-6b0d92cf4d22
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Whether BigQuery answered the query from cache, as a label rather than a boolean. Exists because a legend or slicer over cache_hit reads "True / False", which says nothing about which one is the good outcome; "Cache hit" and "Executed" do. Same data as cache_hit - use whichever suits the visual.
	column 'Cache State' = IF ( 'Fact'[cache_hit], "Cache hit", "Executed" )
		dataType: string
		lineageTag: 8b247e05-3f61-42a9-9c78-1e06d5734bf2
		summarizeBy: none

	/// Day of the week the job was submitted. Derived from the job's own creation date rather than read through dim_Date, so it stays correct in an HTML or SVG measure that iterates Fact directly without an active date relationship in scope.
	column Weekday = FORMAT ( 'Fact'[creation_date], "ddd" )
		dataType: string
		lineageTag: 6d51ba09-8c73-4d2a-b1f6-7ac3e5108933
		summarizeBy: none
		sortByColumn: 'Weekday Order'

	/// Display order for Weekday, Monday first. Hidden - sort key only.
	column 'Weekday Order' = WEEKDAY ( 'Fact'[creation_date], 2 )
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4a0b6e2f-1d95-49c7-8e34-5f2c81a6b7d0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Fact = m
		mode: import
		source =
				let
				    SqlTemplate =
				"
				WITH src AS (
				  -- Filter BEFORE resolving labels so the label pass only runs on kept rows.
				  SELECT *,
				    (SELECT AS STRUCT
				       MAX(IF(key = 'app',           value, NULL)) AS app,
				       MAX(IF(key = 'project',       value, NULL)) AS project,
				       MAX(IF(key = 'env',           value, NULL)) AS env,
				       MAX(IF(key = 'model_name',    value, NULL)) AS model_name,
				       MAX(IF(key = 'resource_type', value, NULL)) AS resource_type,
				       -- dbt-bigquery's OWN label, not one added by this project's query_comment. Present on
				       -- every job dbt submits, including post-hook and run-operation jobs that dbt_artifacts
				       -- never records, and history predating any query_comment change. Equals
				       -- dbt_invocations[command_invocation_id]. Do not swap this for a hand-added run id: a
				       -- per-run value in the query comment also defeats BigQuery's result cache.
				       MAX(IF(key = 'dbt_invocation_id', value, NULL)) AS invocation_id
				     FROM UNNEST(labels)) AS lbl
				  FROM __TABLE__
				  WHERE
				    NOT query like '%INFORMATION_SCHEMA.%'
				    AND state = 'DONE'
				    -- On-demand jobs only. Under a reservation you pay for slot capacity, not bytes, and
				    -- total_bytes_billed keeps being reported without being charged - so reserved jobs would
				    -- add cost to every dollar measure here that nobody was ever billed for. Cost measures
				    -- price bytes, so the fact is scoped to the jobs that pricing model actually applies to.
				    AND reservation_id IS NULL
				    AND creation_time >= TIMESTAMP('" & DateTime.ToText(RangeStart, "yyyy-MM-dd HH:mm:ss") & "')
				    AND creation_time < TIMESTAMP('" & DateTime.ToText(RangeEnd, "yyyy-MM-dd HH:mm:ss") & "')
				),
				
				-- A multi-statement SCRIPT's parent job has no destination_table of its own: the write targets sit
				-- on its child statements. Without this, every script-based model (incrementals, MERGE) collapses
				-- into a single blank bucket -- measured at ~22% of dbt spend. Adopt the destination of the child
				-- that billed the most. Label-independent, so it also repairs history written by a dbt deployment
				-- whose query_comment carried no node name.
				child_dest AS (
				  SELECT
				    parent_job_id,
				    ARRAY_AGG(destination_table.table_id IGNORE NULLS ORDER BY total_bytes_billed DESC LIMIT 1)[SAFE_OFFSET(0)] AS child_table_id
				  FROM src
				  WHERE parent_job_id IS NOT NULL
				  GROUP BY parent_job_id
				),
				
				joined AS (
				  SELECT a.*, COALESCE(a.destination_table.table_id, c.child_table_id) AS raw_dest_table_id
				  FROM src a
				  LEFT JOIN child_dest c ON a.job_id = c.parent_job_id
				)
				
				SELECT
				  '__REGION__' as region,
				  job_id,
				  parent_job_id,
				  user_email,
				  -- Labels: ONE pass over the labels array (was six correlated subqueries).
				  lbl.app AS label_app,
				  lbl.project AS label_project,
				  lbl.env AS label_env,
				  lbl.model_name AS label_model_name,
				  lbl.resource_type AS label_resource_type,
				  lbl.invocation_id AS label_invocation_id,
				  -- Single source of truth for dbt scope. The BigQuery adapter stamps an invocation id on every
				  -- job dbt submits, so this also catches post-hook and run-operation jobs that the run metadata
				  -- never records. Scoping on the app label instead would omit every job submitted without it.
				  -- Every dbt measure and the dbt_attribution column key off this column, so the definition
				  -- changes in one place.
				  lbl.invocation_id IS NOT NULL AS is_dbt_job,
				
				  CASE
				    WHEN statement_type is null THEN 'FAILED'
				    ELSE statement_type
				  END as statement_type,
				  -- The leading /* ... */ query comment is stripped from BOTH the hash and the stored SQL: dbt's
				  -- query_comment carries a per-run invocation_id, which would otherwise make every dbt query
				  -- text unique per run and defeat queryhash dedup. The labels are already columns above.
				  CAST(FARM_FINGERPRINT(REGEXP_REPLACE(query, r'(?s)^\s*/\*.*?\*/\s*', '')) as STRING) as queryhash,
				  REGEXP_REPLACE(query, r'(?s)^\s*/\*.*?\*/\s*', '') as query,
				  cast(creation_time as date) as creation_date,
				  cast(creation_time as time) as creation_time,
				  EXTRACT(HOUR FROM creation_time) AS creation_hour_24,
				  start_time,
				  end_time,
				  TIMESTAMP_DIFF(end_time, start_time, SECOND) AS duration_sec,
				  cache_hit,
				  error_result.reason as error_reason,
				  error_result.location as error_location,
				  error_result.message as error_message,
				  total_bytes_processed,
				  total_bytes_billed,
				  total_slot_ms,
				  TIME(TIMESTAMP_MICROS(total_slot_ms * 1000)) AS total_slot_hr,
				  -- Destination table, normalised:
				  --   SCRIPT parent   -> inherited from its largest child (see child_dest above)
				  --   *__dbt_tmp      -> folded into the parent model, so one model is one bar
				  --   anon*           -> collapsed into a single bucket. These are SELECT results. Kept VISIBLE,
				  --                      not nulled, since they can be a real and surprising share of spend.
				  CASE
				    WHEN a.raw_dest_table_id IS NULL THEN NULL
				    WHEN STARTS_WITH(a.raw_dest_table_id, 'anon') THEN '(anonymous SELECT result)'
				    ELSE REGEXP_REPLACE(a.raw_dest_table_id, r'__dbt_tmp$', '')
				  END AS destination_table_id,
				
				  CASE
				    WHEN total_bytes_processed < 1048576 THEN 1
				    WHEN total_bytes_processed < 104857600 THEN 2
				    WHEN total_bytes_processed < 1073741824 THEN 3
				    ELSE 4
				  END AS DataSizeCategoryID,
				  ---bie---
				  COALESCE(bi_engine_statistics.bi_engine_mode, 'NOT APPLICABLE') AS bie_mode,
				  (
				    SELECT STRING_AGG(r.code, ', ')
				    FROM UNNEST(bi_engine_statistics.bi_engine_reasons) r
				  ) AS bie_error_code,
				
				  (
				    SELECT STRING_AGG(r.message, ' | ')
				    FROM UNNEST(bi_engine_statistics.bi_engine_reasons) r
				  ) AS bie_error_reason
				
				FROM joined a
				",
				
				    // Regions come from the p_Regions parameter.
				    Regions = List.Transform(Text.Split(p_Regions, ","), Text.Trim),
				
				    Tables = List.Transform(
				        Regions,
				        (r) =>
				            try fx_GetJobdetails(r, SqlTemplate)
				            otherwise null
				    ),
				
				    // Remove failed/null queries
				    CleanTables = List.RemoveNulls(Tables),
				
				    Combined = Table.Combine(CleanTables),
				
				    // Sample-data branch. The date filter is not optional: the refresh
				    // policy above binds RangeStart/RangeEnd per partition, and a CSV read
				    // that ignored them would return every row for every partition.
				    _csv = () =>
				        let
				            _all = fn_ReadSampleCsv("jobs.csv", {
				            {"job_id", type text}, {"creation_date", type date}, {"creation_time", type time}, {"start_time", type datetime},
				            {"end_time", type datetime}, {"duration_sec", Int64.Type}, {"cache_hit", type logical}, {"creation_hour_24", Int64.Type},
				            {"total_slot_hr", type time}, {"DataSizeCategoryID", Int64.Type}, {"total_bytes_processed", Int64.Type}, {"total_bytes_billed", Int64.Type},
				            {"error_reason", type text}, {"error_location", type text}, {"error_message", type text}, {"user_email", type text},
				            {"statement_type", type text}, {"queryhash", type text}, {"region", type text}, {"bie_mode", type text},
				            {"label_app", type text}, {"label_project", type text}, {"bie_error_code", type text}, {"bie_error_reason", type text},
				            {"label_env", type text}, {"parent_job_id", type text}, {"label_model_name", type text}, {"label_resource_type", type text},
				            {"label_invocation_id", type text}, {"total_slot_ms", Int64.Type}, {"destination_table_id", type text}, {"query", type text},
				            {"is_dbt_job", type logical}
				            }),
				            _window = Table.SelectRows(
				                _all,
				                each [creation_date] >= DateTime.Date(RangeStart)
				                    and [creation_date] < DateTime.Date(RangeEnd)
				            )
				        in
				            _window,
				
				    Source = if p_DataSource = "SampleCSV" then _csv() else Combined
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

